version: "3"

services:
    db:
        image: mariadb
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MARIADB_ROOT_PASSWORD: ROOT_PASSWORD
            MARIADB_DATABASE: DATABASE_NAME
            MARIADB_USER: USER_NAME
            MARIADB_PASSWORD: USER_PASSWORD
        ports:
            - 3306:3306


    php:
        build:
            context: ./docker/php
        depends_on:
            - db
        volumes:
            - .:/var/www/html/


    nginx:
        image: nginx:latest
        depends_on:
            - db
        volumes:
            - .:/var/www/html/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 80:80
        links:
            - php

volumes:
  db_data:

